### ISSUE TITLE
可以给我解释下你写的create Suite的函数嘛，就是动态导入这块，这块一直编译有问题，我找不到原因额。多谢！！

### ISSUE THREAD

**Issue by lynnxia517** [wuranxu/webTest#5]
D:\Python\Python36\python.exe D:/temp/Automated-Test-master/run.py
Traceback (most recent call last):
  File "D:/temp/Automated-Test-master/run.py", line 43, in <module>
    suite = create_suite()
  File "D:/temp/Automated-Test-master/run.py", line 18, in create_suite
    cls_name = importlib.import_module("{}.{}.{}".format(Config.suite_name, v, k))
  File "D:\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests.tests'

**Comment by wuranxu** [comment]
有试过重新安装Python或者更换版本试试嘛？别人没有出现过这个问题，我这边Python3.6测试过也是正常的。这个看起来是importlib内部的错误~

**Comment by lynnxia517** [comment]
嗯 工程本身没问题。被我搞坏了。
